name: .NET Review Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.1

      - name: Install Dependencies
        run: 
          python -m pip install --upgrade pip
          pip install openai PyGithub python-dotenv

      - name: Run Review Bot
        run: python3 review_bot/review_bot.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
