# .github/workflows/test-action.yml
name: Test PR Bot Trigger

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello from PR
        run: echo "✅ Workflow triggered on PR #${{ github.event.pull_request.number }}"
